CREATE TABLE TB_GAME(
    ID_GAME INT
    ,NM_GAME VARCHAR(70) NOT NULL
    ,ID_PLATAFORM INT NOT NULL
    ,DE_DESCRIPTION VARCHAR(250)
,NM_DEVELOPER VARCHAR(30)
    
,NM_GENRE VARCHAR(30)

    ,CONSTRAINT PK_GAME PRIMARY KEY(ID_GAME)
);

CREATE TABLE TB_PLATAFORM(
    ID_PLATAFORM INT
    ,NM_PLATAFORM VARCHAR(30) NOT NULL
    ,DE_DESCRIPTION VARCHAR(250)

    ,CONSTRAINT PK_PLATAFORM PRIMARY KEY(ID_PLATAFORM)
);

ALTER TABLE TB_GAME ADD CONSTRAINT FK_PLATAFORM_GAME FOREIGN KEY(ID_PLATAFORM) REFERENCES TB_PLATAFORM;

CREATE TABLE TB_USER(
    ID_USER INT 
    ,DE_EMAIL VARCHAR(250) NOT NULL 
    ,VL_PASSW VARCHAR(30) NOT NULL
    ,NM_USER VARCHAR(70) UNIQUE
    ,DT_REGISTER DATE DEFAULT SYSDATE

    ,CONSTRAINT PK_USER PRIMARY KEY(ID_USER)
);

CREATE TABLE TB_GAME_GRADES(
    ID_GAME INT NOT NULL
    ,ID_USER INT NOT NULL
    ,VL_GRADE FLOAT NOT NULL CHECK (VL_GRADE >= 0 AND VL_GRADE <= 10)
    ,DT_GRADE DATE DEFAULT SYSDATE

    ,CONSTRAINT PK_GAME_GRADE PRIMARY KEY(ID_GAME,ID_USER)
);

ALTER TABLE TB_GAME_GRADES ADD CONSTRAINT FK_GRADE_GAME FOREIGN KEY(ID_GAME) REFERENCES TB_GAME;
ALTER TABLE TB_GAME_GRADES ADD CONSTRAINT FK_GRADE_USER FOREIGN KEY(ID_USER) REFERENCES TB_USER;

CREATE TABLE TB_GAME_COMMENTS(
    ID_COMMENT INT
    ,DE_COMMENT VARCHAR2(255)
    ,ID_GAME INT NOT NULL
    ,ID_USER INT NOT NULL
    ,DT_COMMENT DATE DEFAULT SYSDATE

    ,CONSTRAINT PK_COMMENTS PRIMARY KEY(ID_GAME,ID_USER)
);

ALTER TABLE TB_GAME_COMMENTS ADD CONSTRAINT FK_COMMENT_GAME FOREIGN KEY(ID_GAME) REFERENCES TB_GAME;
ALTER TABLE TB_GAME_COMMENTS ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY(ID_USER) REFERENCES TB_USER;


CREATE VIEW VW_GAMEFULL AS SELECT GA.ID_GAME, GA.NM_GAME, PL.NM_PLATAFORM,GA.NM_DEVELOPER,GA.NM_GENRE,GA.DE_DESCRIPTION,PL.ID_PLATAFORM FROM TB_GAME GA INNER JOIN TB_PLATAFORM PL ON GA.ID_PLATAFORM = PL.ID_PLATAFORM;

CREATE VIEW VW_COMMENT AS
SELECT ID_COMMENT, C.ID_USER, U.NM_USER, C.ID_GAME, G.NM_GAME ,DE_COMMENT,DT_COMMENT FROM TB_GAME_COMMENTS C
INNER JOIN TB_USER U ON C.ID_USER = U.ID_USER
INNER JOIN TB_GAME G ON C.ID_GAME = G.ID_GAME;