CREATE OR REPLACE TRIGGER TG_PK_GAME 
BEFORE INSERT 
ON TB_GAME
FOR EACH ROW
DECLARE 
    IDG INT;
BEGIN
    SELECT SQ_GAME.NEXTVAL INTO IDG FROM DUAL;
    :NEW.ID_GAME := IDG;
END;

CREATE OR REPLACE TRIGGER TG_PK_PLATAFORM 
BEFORE INSERT 
ON TB_PLATAFORM
FOR EACH ROW
DECLARE
    IDP INT;
BEGIN
    SELECT SQ_PLATAFORM.NEXTVAL INTO IDP FROM DUAL;
    :NEW.ID_PLATAFORM := IDP;
END;

CREATE OR REPLACE TRIGGER TG_PK_USER 
BEFORE INSERT 
ON TB_USER
FOR EACH ROW
DECLARE
    IDU INT;
BEGIN
    SELECT SQ_USER.NEXTVAL INTO IDU FROM DUAL;
    :NEW.ID_USER := IDU;
END;

CREATE OR REPLACE TRIGGER TG_UPDATE_GAME_AVERAGE
AFTER INSERT OR UPDATE
ON TB_GAME_GRADES
FOR EACH ROW
DECLARE NEW_AVG DECIMAL(3,2);
BEGIN
    SELECT AVG(VL_GRADE) INTO NEW_AVG FROM TB_GAME_GRADES WHERE ID_GAME = :NEW.ID_GAME;
    UPDATE TB_GAME SET VL_AVG_SCORE = NEW_AVG WHERE ID_GAME = :NEW.ID_GAME;
END;