ALTER TABLE TB_GAME ADD (NM_DEVELOPER VARCHAR(30), NM_GENRE VARCHAR(30));

BEGIN
    FOR DEV IN
    (SELECT NM_DEVELOPER FROM TB_GAME)
    LOOP
       UPDATE TB_GAME SET NM_DEVELOPER = UPPER(DEV.NM_DEVELOPER) WHERE NM_DEVELOPER = DEV.NM_DEVELOPER;
    END LOOP;
END;

BEGIN
    FOR DEV IN
    (SELECT NM_GENRE FROM TB_GAME)
    LOOP
       UPDATE TB_GAME SET NM_GENRE = UPPER(DEV.NM_GENRE) WHERE NM_GENRE = DEV.NM_GENRE;
    END LOOP;
END;